# Generated by Django 4.2.6 on 2023-10-11 15:49

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_location_latitude_location_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
