# Generated by Django 4.2.6 on 2023-11-17 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0002_remove_location_description_remove_location_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_locations', to=settings.AUTH_USER_MODEL),
        ),
    ]
