# Generated by Django 4.2.6 on 2023-11-09 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_locationtype_location_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maps.locationtype'),
        ),
    ]
