# Generated by Django 4.2.6 on 2023-11-23 17:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maps', '0003_location_favorited_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='confirmed_by',
            field=models.ManyToManyField(related_name='confirmed_locations', to=settings.AUTH_USER_MODEL),
        ),
    ]
