# Generated by Django 4.2.6 on 2023-10-25 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_location_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='country',
        ),
        migrations.RemoveField(
            model_name='location',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='location',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='status',
        ),
        migrations.AddField(
            model_name='location',
            name='description',
            field=models.TextField(default='placeholder'),
        ),
        migrations.AddField(
            model_name='location',
            name='name',
            field=models.CharField(default='placeholder', max_length=100),
        ),
    ]
