# Generated by Django 4.2.6 on 2023-10-25 15:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_location_latitude_location_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='location',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
